version: '3'
services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: dbpassword
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db-backup:/docker-entrypoint-initdb.d
    restart: always
  drupal:
    environment:
      - PHP_IDE_CONFIG=serverName=172.17.0.1
    depends_on:
      - db
    image: emergya-drupal:0.2
    ports:
      - "2443:443"
    volumes:
      - ./:/opt/drupal
      - /opt/drupal/vendor
    restart: always
